HealthyMan/Areas/Admin/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.IO.Ports;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Threading.Tasks;
using HealthyMan.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HealthyMan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ConfigurationController : Controller
    {
        private SerialPort serialPort;
        public IActionResult Index()
        {
            ESP8266ConnectionData eSP8266ConnectionData = new ESP8266ConnectionData();

            eSP8266ConnectionData.MqttServerIpAdress = GetLocalIPAddress();
            ViewBag.PortNames = new List<SelectListItem>();
            foreach (string portName in SerialPort.GetPortNames())
            {
                ViewBag.PortNames.Add(new SelectListItem() { Text = portName, Value = portName });
            }
            
            return View(eSP8266ConnectionData);
        }

        [HttpPost]
        public IActionResult SendConnectionDataToESP8266(ESP8266ConnectionData eSP8266ConnectionData)
        {
            serialPort = new SerialPort(eSP8266ConnectionData.PortName, 115200, System.IO.Ports.Parity.None, 8, System.IO.Ports.StopBits.One);
            serialPort.Open();
            serialPort.Write($"config:{eSP8266ConnectionData.SSID}:{eSP8266ConnectionData.Password}:{eSP8266ConnectionData.MqttServerIpAdress}");
            serialPort.Close();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult MosquittoConfFile()
        {
            return File("~/configuration/mosquitto.conf", "text/plain", "mosquitto.conf");
        }

        private static string GetLocalIPAddress()
        {
            var host = Dns.GetHostEntry(Dns.GetHostName());
            foreach (var ip in host.AddressList)
            {
                if (ip.AddressFamily == AddressFamily.InterNetwork)
                {
                    return ip.ToString();
                }
            }

            return "Exception";
        }
    }
}

HealthyMan/Areas/Admin/Controllers/MeasurementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HealthyMan.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HealthyMan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MeasurementController : Controller
    {
        private readonly ApplicationDbContext _context;
        public MeasurementController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Settings.SingleOrDefaultAsync(s => s.SettingsId == 1));
        }

    }
}

HealthyMan/Areas/Admin/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HealthyMan.Data;
using HealthyMan.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HealthyMan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PatientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PatientsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Patients.ToListAsync());
        }

        public async Task<IActionResult> Patient(int id)
        {
            return View(await _context.Patients.Include(p => p.Measurements).SingleOrDefaultAsync(p => p.PatientId == id));
        }
        public async Task<IActionResult> DeletePatient(int id)
        {
            return View(await _context.Patients.Include(p => p.Measurements).SingleOrDefaultAsync(p => p.PatientId == id));
        }

        public async Task<IActionResult> DeletePatientConfirmed(int id)
        {
            HealthyMan.Models.Patient patient = await _context.Patients.SingleOrDefaultAsync(p => p.PatientId == id);
            
            List<Measurement> measurements = _context.Measurements.Where(m => m.Patient.PatientId == id).ToList();

            _context.Measurements.RemoveRange(measurements);
            _context.Patients.Remove(patient);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Measurement(int id)
        {
            return View(await _context.Measurements.Include(m => m.Patient).SingleOrDefaultAsync(m => m.MeasurementId == id));
        }

        public async Task<IActionResult> DeleteMeasurement(int id)
        {
            return View(await _context.Measurements.Include(m => m.Patient).SingleOrDefaultAsync(m => m.MeasurementId == id));
        }

        public async Task<IActionResult> DeleteMeasurementConfirmed(int measurementId, int patientId)
        {
            Measurement measurement = await _context.Measurements.SingleOrDefaultAsync(m => m.MeasurementId == measurementId);
            _context.Measurements.Remove(measurement);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Patient),new { id = patientId });
        }
        

    }
}

HealthyMan/Areas/Admin/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HealthyMan.Data;
using HealthyMan.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HealthyMan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SettingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SettingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            await CreateDefaultSettings();

            ViewBag.PulseProcessingMethods = new List<SelectListItem>();
            ViewBag.PulseProcessingMethods.Add(new SelectListItem() { Text = "find peaks", Value = "find peaks" });
            ViewBag.PulseProcessingMethods.Add(new SelectListItem() { Text = "double mean", Value = "double mean" });
            return View(await _context.Settings.SingleOrDefaultAsync(s => s.SettingsId == 1));
        }

        private async Task CreateDefaultSettings()
        {
            Settings settings = await _context.Settings.SingleOrDefaultAsync(s => s.SettingsId == 1);
            if (settings == null)
            {
                settings = new Settings();
                settings.SettingsId = 1;
                settings.PulseFFTWindowSize = 128;
                settings.PulseFFTWindowSizeWithPadding = 1024;
                settings.PulseFFTStepSize = 10;
                settings.PulseProcessingMethod = "find peaks";

                settings.RespiratoryRateFFTWindowSize = 256;
                settings.RespiratoryRateFFTWindowSizeWithPadding = 2048;
                settings.RespiratoryRateFFTStepSize = 255;

                await _context.AddAsync(settings);
                await _context.SaveChangesAsync();
            }
        }

        public async Task<IActionResult> SetDefaultSettings()
        {
            Settings currentSettigns = await _context.Settings.SingleOrDefaultAsync(s => s.SettingsId == 1);

            currentSettigns.PulseFFTWindowSize = 128;
            currentSettigns.PulseFFTWindowSizeWithPadding = 1024;
            currentSettigns.PulseFFTStepSize = 10;
            currentSettigns.PulseProcessingMethod = "find peaks";

            currentSettigns.RespiratoryRateFFTWindowSize = 256;
            currentSettigns.RespiratoryRateFFTWindowSizeWithPadding = 2048;
            currentSettigns.RespiratoryRateFFTStepSize = 255;

            _context.Update(currentSettigns);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> SaveSettings(Settings settings)
        {
            Settings currentSettigns = await _context.Settings.SingleOrDefaultAsync(s => s.SettingsId == 1);
            currentSettigns.PulseFFTWindowSize = settings.PulseFFTWindowSize;
            currentSettigns.PulseFFTWindowSizeWithPadding = settings.PulseFFTWindowSizeWithPadding;
            currentSettigns.PulseFFTStepSize = settings.PulseFFTStepSize;
            currentSettigns.PulseProcessingMethod = settings.PulseProcessingMethod;

            currentSettigns.RespiratoryRateFFTWindowSize = settings.RespiratoryRateFFTWindowSize;
            currentSettigns.RespiratoryRateFFTWindowSizeWithPadding = settings.RespiratoryRateFFTWindowSizeWithPadding;
            currentSettigns.RespiratoryRateFFTStepSize = settings.RespiratoryRateFFTStepSize;

            _context.Update(currentSettigns);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

       
    }
}

HealthyMan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthyMan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HealthyMan</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_NavigationPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HealthyMan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HealthyMan/Views/Shared/_NavigationPartial.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link font-weight-bold" asp-area="Admin" asp-controller="Patients" asp-action="Index">Patients</a>
    </li>

    <li class="nav-item">
        <a class="nav-link font-weight-bold" asp-area="Admin" asp-controller="Measurement" asp-action="Index">Measurement</a>
    </li>

    <li class="nav-item">
        <a class="nav-link font-weight-bold" asp-area="Admin" asp-controller="Settings" asp-action="Index">Settings</a>
    </li>

    <li class="nav-item">
        <a class="nav-link font-weight-bold" asp-area="Admin" asp-controller="GSRCalibration" asp-action="Index">GSR Calibration</a>
    </li>
    <li class="nav-item">
        <a class="nav-link font-weight-bold" asp-area="Admin" asp-controller="Configuration" asp-action="Index">Configuration</a>
    </li>
    <li class="nav-item">
        <a class="nav-link font-weight-bold" asp-area="Admin" asp-controller="PulseProcessingJs" asp-action="Index"><i>PulseProcessing.js</i></a>
    </li>
    <li class="nav-item">
        <a class="nav-link font-weight-bold" asp-area="Admin" asp-controller="RespiratoryRateProcessingJS" asp-action="Index"><i>RespiratoryRateProcessing.js</i></a>
    </li>
</ul>